WebAppCoreWithView/Models/ErrorViewModel.cs
namespace WebAppCoreWithView.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebAppCoreWithView/Models/User.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace WebAppCoreWithView.Models
{
    [Table("User")]
    public class User
    {
        public long Id { get; set; }
        public string? UserName { get; set; }
        public string? Password { get; set; }
        public string? FirstName { get; set; }
        public string? SurName { get; set; }
        public DateTime? CreateDate { get; set; }
        public bool? Active { get; set; }
        public string? Type { get; set; }
        public string? Email { get; set; }
    }
}

WebAppCoreWithView/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebAppCoreWithView.Models;

namespace WebAppCoreWithView.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            User user = new User();
            user.FirstName = "Test";
            user.FirstName = "Test";
            

            return View(user);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebAppCoreWithView/Controllers/TestUserController.cs
using Microsoft.AspNetCore.Mvc;
using WebAppCoreWithView.Interface;
using WebAppCoreWithView.Models;

namespace WebAppCoreWithView.Controllers
{
    public class TestUserController : Controller
    {
        private readonly IUser _IUser;
        

        public TestUserController(IUser iUser)
        {
            _IUser = iUser;
        }

        [HttpPost]
        public IActionResult Save([FromBody] User user)
        {
            try
            {
                _IUser.SaveUser(user);

                return base.Json("Save");
            }
            catch (Exception)
            {

                throw;
            }
        }

        [HttpPost]
        public IActionResult Update([FromBody] User user)
        {
            try
            {
                _IUser.UpdateUser(user);

                return base.Json("Update");
            }
            catch (Exception)
            {

                throw;
            }
        }
    }
}

WebAppCoreWithView/Controllers/TestViewController.cs
using Microsoft.AspNetCore.Mvc;
using WebAppCoreWithView.Interface;
using WebAppCoreWithView.Models;

namespace WebAppCoreWithView.Controllers
{
    public class TestViewController : Controller
    {
        private IUser _IUser;

        public TestViewController(IUser iUser)
        {
            _IUser = iUser;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Save(User user)
        {
            try
            {
                _IUser.SaveUser(user);

                return base.Json("Save");
            }
            catch (Exception)
            {

                throw;
            }
        }


        [HttpGet]
        public IActionResult Login()
        {
            try
            {
                List<User> users = new List<User>();

                User user = new User();
                user.FirstName = "Test";
                user.Email = "Test@email.com";
                users.Add(user);

                return View(users);
                //return (IEnumerable<User>)View(users);
            }
            catch (Exception)
            {

                throw;
            }
        }
    }
}

WebAppCoreWithView/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model WebAppCoreWithView.Models.User




<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

    <h2>@Model.FirstName</h2>
</div>

WebAppCoreWithView/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppCoreWithView</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppCoreWithView.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppCoreWithView</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TestView" asp-action="login">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebAppCoreWithView - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebAppCoreWithView/Views/TestView/Login.cshtml
@{
    //ViewData["Title"] = "Login";
}
@*@model WebAppCoreWithView.Models.User*@
@model List<WebAppCoreWithView.Models.User>

<h2>Index</h2>

<p>Hello from our View Template login !</p>
<table border="1" cellpadding="4">
        @foreach (var row in Model)
        {
        <tr>
            <td>@row.FirstName</td>
            <td>@row.Email</td>
        </tr>
    }
    </table>